//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cursoNET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userTable
    {
        public int idUser { get; set; }
        public string userEmail { get; set; }
        public string userPassword { get; set; }
        public int fkState { get; set; }
        public Nullable<int> userAge { get; set; }
    
        public virtual statesTable statesTable { get; set; }
    }
}
